# Generated by Django 3.0.2 on 2020-01-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_nav',
            field=models.BooleanField(default=False, verbose_name='是否导航'),
        ),
    ]
